name: tcpdump
version: 0.1
summary: Testing Permissions
description:
  Testing raw packet access

parts:
  tcpdump:
    plugin: autotools
    source: https://github.com/the-tcpdump-group/tcpdump.git
    source-type: git
    build-packages: [libpcap-dev]
    

apps:
  tcpdump-test:
    command: tcpdump
    plugs: [network, network-bind, raw-usb]
